repos:
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
        hooks:
          -   id: isort
              types: [ python ]
              additional_dependencies: [ pipreqs, pip-api, six ]
              verbose: true
    -   repo: https://github.com/psf/black
        rev: 20.8b1 # Replace by any tag/version: https://github.com/psf/black/tags
        hooks:
          -   id: black
              language_version: python3 # Should be a command that runs python3.6+]
              exclude: ^.*\b(migrations)\b.*$
